name: fail_pipeline.yaml
on: 
    push:
        branches: 
          - v[0-9].[0-9]

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.commits[0].message,'#NORUN')}}

    steps:    
        - 
            name: Checkout
            uses: actions/checkout@v4
        -
            name: Check commit message
            run: |
                MyCommit1=$(git log -1 --pretty=%B)
                if [[ $MyCommit1 == *"#NORUN"* ]]; then
                    exit 1
                fi
        -
            name: Checkout code
            uses: actions/checkout@v3
        -
            name: Run Trivy vulnerability scanner in repo mode
            uses: aquasecurity/trivy-action@master
            with:
              scan-type: 'fs'
              ignore-unfixed: true
              format: 'table'
              output: 'trivy-results.txt'
              severity: 'HIGH'
        - 
            name: Slack Notification
            if: failure()
            uses: rtCamp/action-slack-notify@v2
            env:
              SLACK_COLOR: ${{job.status}}
              SLACK_CHANNEL: mytest
              SLACK_MESSAGE: This is my message.
              SLACK_TITLE: cicdworkshop
              SLACK_USERNAME: DipSA 57 CICD
              SLACK_WEBHOOK: ${{ secrets.WEBHOOK_URL }}
#Upload scan report
        -
            name: Upload scan report
            if: failure()
            uses: MeilCli/slack-upload-file@v3
            with:
              slack_token: ${{ secrets.SLACK_BOT_TOKEN }}
              channel_id: ${{ secrets.CHANNEL_ID }}
              file_path: 'trivy-results.txt'
              initial_comment: MyMessage
        -
            name: Checkout
            uses: actions/checkout@v3
        -
            name: Set up QEMU
            uses: docker/setup-qemu-action@v3
        -
            name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3
        -
            name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_SECRET }}
        -
            name: Build and push
            uses: docker/build-push-action@v5
            with:
              context: .
              push: true
              tags: dingzeyu/cicdworkshop:${{github.sha}}
        -
            uses: actions/checkout@v3.5.2
            with:
              fetch-depth: 1
        - 
            name: Install Cosign
            uses: sigstore/cosign-installer@v3.1.1
            with:
              cosign-release: 'v2.1.1'
        - 
            name: Sign image with a key
            run: |
              cosign sign --yes --key env://COSIGN_PRIVATE_KEY "${TAGS}"
            env:
              TAGS: dingzeyu/cicdworkshop:${{github.sha}}
              COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
              COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
        - 
            name: Slack Notification
            uses: rtCamp/action-slack-notify@v2
            env:
              SLACK_CHANNEL: mytest
              SLACK_MESSAGE: | 
                Name: Ding Zeyu
                Matriculation: e1221840
                *Email*:e1221840@u.nus.edu
                *Git*: https://github.com/${{ github.repository }}
                *Image*: https://hub.docker.com/repository/docker/dingzeyu/cicdworkshop/
              SLACK_TITLE: cicdworkshop
              SLACK_USERNAME: DipSA 57 CICD
              SLACK_WEBHOOK: ${{ secrets.WEBHOOK_URL }}
        